### PR TITLE
Added metric ESP32 project 

### PR DESCRIPTION
**Pull request by Breinbjerg**
- Bare minimum TFLU project to run inference on target 
- Created CC array with input data
- Running inference 10x times 
- Getting used RAM 
- Prints results to console. 
- Currently there's a placeholder in `components` for the updated version of the model. Waiting implementation from @waveworks-ai 
- Enabled toggle between model v1 and v2 with `Kconfig`
  - In the project folder run `idf.py menuconfig` 
  - Will open GUI in terminal. Added a new menu `Project settings`
image

### Example run 

image

### CODE REVIEW

**Comment by waveworks-ai** [comment]
Looks good to me.. except, is there a way to do this without putting the generated model code (for model v2) in the repository? Since it's generated from Python and will be different for everyone. For example, remove esp32_metric/components/model_version_2 and make the Python code write that stuff instead?

**Comment by Breinbjerg** [comment]
Idea: I merge this and in your pr you just add few more lines and save the generated model to component folder as well? 

Then we can wrap up afterwards with defines etc etc so it All fits?

**Comment by waveworks-ai** [comment]
Deal! :)

**Comment by waveworks-ai** [comment]
I'm merging this branch into the model_v2 branch, so you don't need to merge this one.

**Review by waveworks-ai — APPROVED** [review]

**Comment by Breinbjerg** [comment]
Closing this one since it's part of the other PR.

**Pull request closed without merging**
